project_name: Predictive_Maintenance_v1
author: Krishna Chaitanya G
data:
  data_dir: data/
  raw_dir: data/raw/
  raw_data_file: data/raw/new_data.csv
  processed_dir: data/processed/
  production_dir: data/production/
  manifest_path: data/manifest.txt
  metadata_path: data/metadata.json
  curr_version: v2.0.0
model:
  model_dir: models/
  train_data_file: data/processed/v2.1.1_scaled.csv
  metadata_path: models/metadata.json
preprocess:
  target_column: Machine failure
  stratify: Machine failure
model_params:
  algorithm: LogisticRegression
  class_weights: balanced
  max_depth: 10
  val_size: 0.2
  max_iter: 3000
  random_state: 42
deployment:
  model_path: models/v2_LogisticRegression_model.joblib
  results_dir: results/
  results_file: results.csv
  model_log_path: deployment_logs.csv
  port: 5000
  debug: true
  threshold: 0.55
